CREATE DATABASE FINAL_PROJECT
CREATE TABLE ADMIN_INFOR
(
NAME VARCHAR(50) NOT NULL UNIQUE,
AGE VARCHAR(50) NOT NULL,
GENDER VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CONTACT_NO VARCHAR(50) NOT NULL,
PASSWOARD VARCHAR(50) NOT NULL UNIQUE,
PICTURE IMAGE
);
INSERT INTO ADMIN_INFOR VALUES('ADMIN','20','MALE','RAJSHAHI','XXX-XXXXXXXX','ADMIN',NULL);
SELECT *FROM ADMIN_INFOR


CREATE TABLE ATTENDANT_INFO
(
ID int IDENTITY(20210, 1) PRIMARY KEY, 
NAME VARCHAR(50) NOT NULL,
AGE VARCHAR(50) NOT NULL,
GENDER VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CONTACT_NO VARCHAR(50) NOT NULL,
PASSWOARD VARCHAR(50) NOT NULL UNIQUE,
PICTURE IMAGE
)

SELECT *FROM ATTENDANT_INFO

INSERT INTO ATTENDANT_INFO VALUES('ADMIN','20','MALE','RAJSHAHI','XXX-XXXXXXXX','ADMIN');

DROP TABLE ATTENDANT_INFO




CREATE TABLE CUSTOMER_INFO
(
ID int IDENTITY(101, 1) PRIMARY KEY, 
NAME VARCHAR(50) NOT NULL,
AGE VARCHAR(50) NOT NULL,
GENDER VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CONTACT_NO VARCHAR(50) NOT NULL,
PASSWOARD VARCHAR(50) NOT NULL UNIQUE,
PICTURE IMAGE
);

SELECT *FROM CUSTOMER_INFO



CREATE TABLE FLOOR_INFOR
(
FLOOR_NAME VARCHAR(50) NOT NULL,
SPOT_NAME VARCHAR(50) NOT NULL UNIQUE,
PARKING_TYPE VARCHAR(50) NOT NULL,
PARKING_STATUS VARCHAR(50) NOT NULL,
RATE VARCHAR(50) NOT NULL

);

SELECT *FROM FLOOR_INFOR



